/**********************************************************************************************************************
 *                                                Class SettingsDialog
 *********************************************************************************************************************/
package AsterTracker;

/**
 * Class SettingsDialog displays settings and provides the ability load, edit and save them.
 *
 * @author Tony Evans
 */
public class SettingsDialog extends javax.swing.JDialog {

    private final Settings settings;     // pointer to settings data

   /**
    * Create dialog and initialise fields.
     * @param parent Parent Frame.
     * @param modal Is it Modal.
     * @param s Settings.
    */
    public SettingsDialog(java.awt.Frame parent, boolean modal, Settings s) {
        super(parent, modal);
        settings = s;
        initComponents();
    }

   /**
    * Create the form. Do NOT modify this code that has been generated by Netbeans.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        black = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        white = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        minMotion = new javax.swing.JSpinner();
        maxMotion = new javax.swing.JSpinner();
        minPA = new javax.swing.JSpinner();
        maxPA = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        blur = new javax.swing.JCheckBox();
        flatten = new javax.swing.JCheckBox();
        deline = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        fileName = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        sigma1 = new javax.swing.JSpinner();
        trkerr = new javax.swing.JSpinner();
        posErr1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        aperture = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        tcount1 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        sigma2 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton3.setText("Save As");
        jButton3.setToolTipText("Adopt these settings and save to a new configuration file.");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doSaveAs(evt);
            }
        });

        jButton4.setText("OK");
        jButton4.setToolTipText("Adopt these settings without saving changes in the configuration file.");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doOK(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Display settings"));

        black.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(3.0f), Float.valueOf(0.0f), Float.valueOf(8.0f), Float.valueOf(0.1f)));
        black.setToolTipText("Black level expressed as sigmas of the noise profile below background.");

        jLabel2.setText("Black level (sigmas below background)");

        white.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(9.0f), Float.valueOf(0.0f), Float.valueOf(20.0f), Float.valueOf(0.1f)));
        white.setToolTipText("White level expressed as sigmas of the noise profile above background.");

        jLabel3.setText("White level (sigmas above background)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(white)
                    .addComponent(black))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(black, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(white, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Synthetic tracking"));

        minMotion.setModel(new javax.swing.SpinnerNumberModel(0.25f, 0.1f, null, 0.05f));
        minMotion.setToolTipText("Slowest object to be detected in arcseconds per minute.");

        maxMotion.setModel(new javax.swing.SpinnerNumberModel(6.0f, 0.5f, null, 0.05f));
        maxMotion.setToolTipText("Fastest object to be detected in arcseconds per minute.");

        minPA.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(359.0f), Float.valueOf(1.0f)));
        minPA.setToolTipText("Starting position ange to be searched for moving objects. (degrees).");

        maxPA.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(360.0f), Float.valueOf(1.0f), Float.valueOf(360.0f), Float.valueOf(1.0f)));
        maxPA.setToolTipText("Ending position angle to be searched for moving objects. (degrees).");

        jLabel7.setText("Minimum motion \"/m");

        jLabel8.setText("Maximum motion \"/m");

        jLabel10.setText("Minimum PA°");

        jLabel11.setText("Maximum PA°");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(minMotion)
                    .addComponent(maxMotion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(79, 79, 79)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(minPA)
                    .addComponent(maxPA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minMotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxMotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Processing Options"));

        blur.setSelected(true);
        blur.setText("Do 3x3 smoothing filter on FITS load");
        blur.setToolTipText("Select to run a 3x3 blur filter on all FITS. (Normally increases sensitivity of objects).");
        blur.setActionCommand("blur");
        blur.setBorderPaintedFlat(true);

        flatten.setSelected(true);
        flatten.setText("Use synthetic flat.");
        flatten.setToolTipText("Construct and use a synthetic flat frame on all FITS. (Must have plenty of FITS).");
        flatten.setActionCommand("blur");
        flatten.setBorderPaintedFlat(true);

        deline.setText("Do Vertical Line Reduction");
        deline.setToolTipText("Apply line reduction alogorithm to FITS.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deline)
                    .addComponent(blur)
                    .addComponent(flatten))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(flatten)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deline)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Load");
        jButton1.setToolTipText("Select a configuration file and load it.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doLoad(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.setToolTipText("Save these settings in the current configuration file.");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doSave(evt);
            }
        });

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("Settings");

        cancelButton.setText("Cancel");
        cancelButton.setToolTipText("Close the dialog without changing the settins that were in effect before it was opened.");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doCancel(evt);
            }
        });

        fileName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fileName.setText("Config file name.");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Rules"), "Rules", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(51, 51, 51))); // NOI18N

        sigma1.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(2.0f), Float.valueOf(0.7f), Float.valueOf(12.0f), Float.valueOf(0.1f)));
        sigma1.setToolTipText("Number of noise profile sigmas above background to set threshold for object detection.");

        trkerr.setModel(new javax.swing.SpinnerNumberModel(0.5f, 0.01f, null, 0.01f));
        trkerr.setToolTipText("Allowed positional error in synthetic tracking (pixels). (Smaller achieves better resolution but longer processing time).");

        posErr1.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 0.1f));
        posErr1.setToolTipText("Maximum allowed error in position of middle object in the track of a Mover (pixels). (Straightness check).");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("  T-Count     Track Err       Position Err             ");

        aperture.setModel(new javax.swing.SpinnerNumberModel(5, 3, 12, 1));
        aperture.setToolTipText("Detection aperture radius  should be approx 2.5 - 3.0 times the typical FWHM (pixels).");

        jLabel4.setText("Sigma1 - Threshold for object detection.");
        jLabel4.setToolTipText("Object detection threshold epressed as noise profile sigmas above background.");

        tcount1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        tcount1.setToolTipText("Minimum flux in a potential object should be equivalent to this many pixels over the threshold.");

        jLabel5.setText("Aperture (pixels)");

        sigma2.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(2.0f), Float.valueOf(1.0f), Float.valueOf(12.0f), Float.valueOf(0.1f)));
        sigma2.setToolTipText("Number of noise profile sigmas above background to set threshold for detection of fixed star mask.");

        jLabel6.setText("Threshold for detection and removal of the bright central regions of stars. Expressed in noise profile sigmas above backgrounnd.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(tcount1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(trkerr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(posErr1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sigma2)
                    .addComponent(sigma1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aperture, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addComponent(jLabel6)))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {posErr1, sigma1, trkerr});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sigma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(aperture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sigma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trkerr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posErr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cancelButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, jButton1, jButton2, jButton3, jButton4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(title)
                        .addGap(2, 2, 2)
                        .addComponent(fileName)
                        .addGap(2, 2, 2)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   /**
    * Load the dialog with current settings being used by the program.
    */
    public void setParams() {
        fileName.setText(settings.settingsFile.getName());
        black.setValue(settings.blackHist);
        white.setValue(settings.whiteHist);
        minMotion.setValue(settings.minMotion);
        maxMotion.setValue(settings.maxMotion);
        minPA.setValue(settings.minPA);
        maxPA.setValue(settings.maxPA);
        blur.setSelected(settings.doBlur);
        flatten.setSelected(settings.flatten);
        deline.setSelected(settings.deLine);
        sigma1.setValue(settings.sigma1);
        sigma2.setValue(settings.sigma2);
        aperture.setValue(settings.aperture);
        tcount1.setValue(settings.tCount1);
        trkerr.setValue(settings.trkErr);
        posErr1.setValue(settings.posErr);
        this.repaint();
    }

   /**
    * Load button has been pressed.
    */
    private void doLoad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doLoad
       settings.findSettingsFile();     // find the file to load
       settings.loadSettings();         // load the file into settings
       setParams();                     // load the settings into this dialog.
       settings.setSettingsFile();      // record filename in ini file
    }//GEN-LAST:event_doLoad

   /**
    * Save button has been pressed.
    */
    private void doSave(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doSave
        setSettings();                  // put dialog settins into program settings
        settings.save();                // save them in current settings file
        fileName.setText(settings.settingsFile.getName());
    }//GEN-LAST:event_doSave

   /**
    * Save As button has been pressed.
    */
    private void doSaveAs(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doSaveAs
        setSettings();                  // put dialog settings into program settings
        settings.saveAs();              // save them as new file
        fileName.setText(settings.settingsFile.getName());
        settings.setSettingsFile();     // record name of settings file in ini file
    }//GEN-LAST:event_doSaveAs

   /**
    * Transfer settings in the dialog into the settings used by the program.
    */
    public void setSettings() {
        settings.blackHist = (float) black.getValue();
        settings.whiteHist = (float) white.getValue();
        settings.minMotion = (float) minMotion.getValue();
        settings.maxMotion = (float) maxMotion.getValue();
        settings.minPA = (float) minPA.getValue();
        settings.maxPA = (float) maxPA.getValue();
        settings.doBlur = blur.isSelected();
        settings.flatten = flatten.isSelected();
        settings.deLine = deline.isSelected();
        settings.sigma1 = (float) sigma1.getValue();
        settings.sigma2 = (float) sigma2.getValue();
        settings.aperture= (int) aperture.getValue();
        settings.tCount1= (int) tcount1.getValue();
        settings.trkErr = (float) trkerr.getValue();
        settings.posErr = (float) posErr1.getValue();
    }

   /**
    * OK button has been pressed.
    */
    private void doOK(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doOK
        setSettings();
        this.dispose();
    }//GEN-LAST:event_doOK

   /**
    * Cancel button has been pressed.
    */
    private void doCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doCancel
        this.dispose();
    }//GEN-LAST:event_doCancel


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner aperture;
    private javax.swing.JSpinner black;
    private javax.swing.JCheckBox blur;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox deline;
    private javax.swing.JLabel fileName;
    private javax.swing.JCheckBox flatten;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner maxMotion;
    private javax.swing.JSpinner maxPA;
    private javax.swing.JSpinner minMotion;
    private javax.swing.JSpinner minPA;
    private javax.swing.JSpinner posErr1;
    private javax.swing.JSpinner sigma1;
    private javax.swing.JSpinner sigma2;
    private javax.swing.JSpinner tcount1;
    private javax.swing.JLabel title;
    private javax.swing.JSpinner trkerr;
    private javax.swing.JSpinner white;
    // End of variables declaration//GEN-END:variables
}
